In [1]:
# check datasets (check if the labels are correct)
import numpy as np

test_label_dir = r'D:\zluo033\DNNTraining\data\datasets\test_data\no_pref_removed\test_label_duel_1_new.npy'
test_label = np.load(test_label_dir)
print(test_label)

[[-1.  1.]
 [-1.  1.]
 [-1.  1.]
 ...
 [-1.  1.]
 [ 1. -1.]
 [-1.  1.]]


In [2]:
test_label_dir = r'D:\zluo033\DNNTraining\data\datasets\test_data\no_pref_removed\test_label_duel_1.npy'
test_label = np.load(test_label_dir)
print(test_label,test_label.shape)

[0. 0. 0. 0. 1. 0. 1. 1. 1. 0. 0. 1. 1. 1. 0. 1. 0. 1. 1. 1. 0. 1. 1. 1.
 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 0. 1. 1. 1. 1. 1. 0. 1. 1. 1.
 1. 0. 1. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 1. 0. 1. 1. 1. 0. 0. 0. 1. 1.
 0. 0. 0. 1. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 1. 1. 1. 1. 0.
 0. 1. 1. 0. 1. 0. 1. 1. 1. 0. 0. 1. 0. 1. 1. 1. 0. 1. 1. 1. 1. 0. 0. 0.
 0. 0. 1. 0. 1. 0. 1. 0. 0. 1. 1. 0. 0. 1. 0. 0. 0. 1. 0. 1. 1. 1. 0. 0.
 0. 0. 1. 0. 1. 0. 1. 1. 1. 1. 0. 0. 1. 0. 0. 1. 0. 0. 0. 1. 0. 1. 1. 0.
 1. 1. 0. 0. 1. 1. 0. 0. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 1. 1. 0. 0. 0. 0. 1. 1. 0. 1. 0. 1. 0. 0. 1. 0. 0. 0. 1. 0. 1. 1. 1. 1.
 0. 1. 1. 1. 0. 1. 0. 1. 0. 0. 1. 0. 1. 0. 0. 1. 0. 1. 0. 1. 1. 1. 1. 1.
 0. 1. 0. 1. 0. 1. 0. 0. 1. 0. 1. 1. 1. 1. 0. 1. 1. 0. 0. 0. 1. 0. 1. 0.
 0. 0. 1. 0. 0. 0. 1. 1. 0. 1. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 0. 0. 0. 0.
 0. 1. 1. 0. 1. 0. 1. 0. 1. 1. 0. 0. 0. 1. 1. 0. 1. 1. 0. 0. 0. 1. 1. 0.
 1. 1. 1. 0. 1. 0. 1. 0. 0. 1. 1. 1. 0. 1. 1. 0. 1.

In [3]:
# Convert the label to simple 0 and 1

training_label_dir = r'D:\zluo033\DNNTraining\data\datasets\training_data\no_pref_removed\train_label_duel_1.npy'
validation_label_dir = r'D:\zluo033\DNNTraining\data\datasets\validation_data\no_pref_removed\val_label_duel_1.npy'
test_label_dir = r'D:\zluo033\DNNTraining\data\datasets\test_data\no_pref_removed\test_label_duel_1.npy'

training_label = np.load(training_label_dir)
validation_label = np.load(validation_label_dir)
test_label = np.load(test_label_dir)

training_label = np.reshape(training_label,(-1,1))
training_label = np.squeeze(training_label)

validation_label = np.reshape(validation_label,(-1,1))
validation_label = np.squeeze(validation_label)

test_label = np.reshape(test_label,(-1,1))
test_label = np.squeeze(test_label)

np.save(r'D:\zluo033\DNNTraining\data\datasets\training_data\no_pref_removed\train_label_duel_1.npy',training_label)
np.save(r'D:\zluo033\DNNTraining\data\datasets\validation_data\no_pref_removed\val_label_duel_1.npy',validation_label)
np.save(r'D:\zluo033\DNNTraining\data\datasets\test_data\no_pref_removed\test_label_duel_1.npy',test_label)

training_label_dir = r'D:\zluo033\DNNTraining\data\datasets\training_data\no_pref_removed\train_label_duel_2.npy'
validation_label_dir = r'D:\zluo033\DNNTraining\data\datasets\validation_data\no_pref_removed\val_label_duel_2.npy'
test_label_dir = r'D:\zluo033\DNNTraining\data\datasets\test_data\no_pref_removed\test_label_duel_2.npy'

training_label = np.load(training_label_dir)
validation_label = np.load(validation_label_dir)
test_label = np.load(test_label_dir)

training_label = np.reshape(training_label,(-1,1))
training_label = np.squeeze(training_label)

validation_label = np.reshape(validation_label,(-1,1))
validation_label = np.squeeze(validation_label)

test_label = np.reshape(test_label,(-1,1))
test_label = np.squeeze(test_label)

np.save(r'D:\zluo033\DNNTraining\data\datasets\training_data\no_pref_removed\train_label_duel_2.npy',training_label)
np.save(r'D:\zluo033\DNNTraining\data\datasets\validation_data\no_pref_removed\val_label_duel_2.npy',validation_label)
np.save(r'D:\zluo033\DNNTraining\data\datasets\test_data\no_pref_removed\test_label_duel_2.npy',test_label)

training_label_dir = r'D:\zluo033\DNNTraining\data\datasets\training_data\no_pref_removed\train_label_duel_3.npy'
validation_label_dir = r'D:\zluo033\DNNTraining\data\datasets\validation_data\no_pref_removed\val_label_duel_3.npy'
test_label_dir = r'D:\zluo033\DNNTraining\data\datasets\test_data\no_pref_removed\test_label_duel_3.npy'

training_label = np.load(training_label_dir)
validation_label = np.load(validation_label_dir)
test_label = np.load(test_label_dir)

training_label = np.reshape(training_label,(-1,1))
training_label = np.squeeze(training_label)

validation_label = np.reshape(validation_label,(-1,1))
validation_label = np.squeeze(validation_label)

test_label = np.reshape(test_label,(-1,1))
test_label = np.squeeze(test_label)

np.save(r'D:\zluo033\DNNTraining\data\datasets\training_data\no_pref_removed\train_label_duel_3.npy',training_label)
np.save(r'D:\zluo033\DNNTraining\data\datasets\validation_data\no_pref_removed\val_label_duel_3.npy',validation_label)
np.save(r'D:\zluo033\DNNTraining\data\datasets\test_data\no_pref_removed\test_label_duel_3.npy',test_label)

training_label_dir = r'D:\zluo033\DNNTraining\data\datasets\training_data\no_pref_removed\train_label_duel_4.npy'
validation_label_dir = r'D:\zluo033\DNNTraining\data\datasets\validation_data\no_pref_removed\val_label_duel_4.npy'
test_label_dir = r'D:\zluo033\DNNTraining\data\datasets\test_data\no_pref_removed\test_label_duel_4.npy'

training_label = np.load(training_label_dir)
validation_label = np.load(validation_label_dir)
test_label = np.load(test_label_dir)

training_label = np.reshape(training_label,(-1,1))
training_label = np.squeeze(training_label)

validation_label = np.reshape(validation_label,(-1,1))
validation_label = np.squeeze(validation_label)

test_label = np.reshape(test_label,(-1,1))
test_label = np.squeeze(test_label)

np.save(r'D:\zluo033\DNNTraining\data\datasets\training_data\no_pref_removed\train_label_duel_4.npy',training_label)
np.save(r'D:\zluo033\DNNTraining\data\datasets\validation_data\no_pref_removed\val_label_duel_4.npy',validation_label)
np.save(r'D:\zluo033\DNNTraining\data\datasets\test_data\no_pref_removed\test_label_duel_4.npy',test_label)


In [4]:
import numpy as np
training_label=np.load(r'D:\zluo033\DNNTraining\data\datasets\training_data\no_pref_removed\train_label_duel_4.npy')
print(training_label,training_label.shape)
validation_label =  np.load(r'D:\zluo033\DNNTraining\data\datasets\validation_data\no_pref_removed\val_label_duel_4.npy')
print(validation_label,validation_label.shape)
test_label=np.load(r'D:\zluo033\DNNTraining\data\datasets\test_data\no_pref_removed\test_label_duel_4.npy')
print(test_label,test_label.shape)

[0. 1. 0. ... 0. 1. 1.] (2671,)
[0. 1. 0. 0. 1. 1. 0. 0. 0. 1. 1. 1. 0. 1. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0.
 1. 1. 1. 0. 0. 0. 1. 1. 1. 1. 1. 0. 1. 1. 1. 0. 1. 0. 0. 0. 0. 1. 0. 0.
 1. 0. 0. 1. 1. 0. 1. 1. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 1. 1. 0.
 1. 0. 1. 0. 0. 0. 1. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 0. 1. 0.
 0. 1. 0. 1. 0. 0. 0. 0. 1. 0. 1. 0. 1. 0. 0. 0. 1. 1. 0. 1. 1. 0. 1. 1.
 0. 1. 1. 1. 1. 0. 1. 1. 0. 0. 1. 0. 0. 1. 1. 0. 1. 1. 1. 1. 0. 0. 1. 1.
 1. 0. 0. 1. 0. 1. 1. 0. 0. 0. 0. 0. 1. 1. 1. 1. 0. 0. 0. 0. 1. 0. 0. 1.
 1. 0. 1. 1. 1. 1. 0. 1. 1. 0. 1. 1. 0. 1. 0. 0. 1. 0. 1. 0. 1. 0. 1. 0.
 0. 1. 0. 1. 0. 0. 1. 1. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 1. 1. 1. 0. 1. 0.
 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 1. 0. 1. 1. 1. 0. 0. 1.
 0. 0. 0. 1. 1. 0. 1. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 1. 1. 0. 0. 0. 1. 0.
 0. 0. 0. 1. 0. 0. 1. 1. 0. 1. 1. 1. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1. 1.
 1. 1. 1. 0. 0. 0. 0. 1. 0. 1. 0. 0. 1. 1. 0. 0. 0. 1. 1. 0. 1. 0. 0. 1.
 0. 0. 1. 0. 0. 0. 

In [5]:
training_label_new = np.load(r'D:\zluo033\DNNTraining\data\datasets\training_data\no_pref_removed\train_label_duel_1_new.npy')
print(training_label_new,training_label_new.shape)

training_label_new = np.reshape(training_label_new,(-1,1))
print(training_label_new,training_label_new.shape)

training_label_new = np.squeeze(training_label_new)
print(training_label_new,training_label_new.shape)

[[ 1. -1.]
 [-1.  1.]
 [-1.  1.]
 ...
 [ 1. -1.]
 [-1.  1.]
 [ 1. -1.]] (2737, 2)
[[ 1.]
 [-1.]
 [-1.]
 ...
 [ 1.]
 [ 1.]
 [-1.]] (5474, 1)
[ 1. -1. -1. ...  1.  1. -1.] (5474,)


In [6]:
np.zeros((len,1))
for i in range(0,len(training_label_new)):


SyntaxError: incomplete input (2175994904.py, line 2)